version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    hostname: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge