version: '3'
services:
  app:
    build:
      context: .. # Le répertoire actuel contient le Dockerfile
    ports:
      - "8080:8080" # Mappez le port 8080 du conteneur sur le port 8080 de l'hôte
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: MyTestDataBase